# 2048
A fun game to play in a not so fun way - through the command line.

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
cd /Users/nathancooperjones/GitHub/2048_ai

/Users/nathancooperjones/GitHub/2048_ai


In [3]:
from twentyfortyeight.game import Game

In [4]:
g = Game()

In [8]:
g.play_interactive(colors=True)

Score: 0, Move Counter: 1
-------------------------

     0     0     0     0
     0     0     0     0
     0     0     0     0
     4     0     2     2

Enter a direction [w/a/s/d or down/up/right/left]: q


KeyboardInterrupt: Goodbye!

In [9]:
g._what_directions_can_we_move()

[True, True, False, True]

In [10]:
g.board

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [4, 0, 2, 2]])

In [14]:
import numpy as np

In [15]:
actions = np.array([1, 2, 3, -1])

g.step(actions)

g.board

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [4, 4, 0, 0]])

In [16]:
import torch

In [32]:
torch.randperm(4) - 2.99

tensor([-0.9900,  0.0100, -2.9900, -1.9900])

## What's Left to Do:
* More verbose debug mode?
* Tracking of all moves made by user, score, move count at time, etc.
* Add documentation to functions.

-----